a:
  enabled: false

b:
  enabled: true
  message: "this is app b"
  replicaCount: 1
  image:
    repository: busybox
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80

