a:
  enabled: true
  message: "this is app a"
  replicaCount: 1
  image:
    repository: busybox
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80

b:
  enabled: false

