{{- if .Values.b.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: b
spec:
  type: {{ .Values.b.service.type }}
  selector:
    app: b
  ports:
    - port: {{ .Values.b.service.port }}
      targetPort: 80
{{- end }}

